version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flutter_web_app
    ports:
      - "8080:80"
    environment:
      AUTH_URL: "https://kobeta.fr/auth"
      FRIENDS_URL: "https://kobeta.fr/friends"
      MESSAGES_URL: "https://kobeta.fr/messages"
      TEAMS_URL: "https://kobeta.fr/teams"
    